// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: queue/kafka/conf.proto

package kafka

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Net with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Net) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Net with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in NetMultiError, or nil if none found.
func (m *Net) ValidateAll() error {
	return m.validate(true)
}

func (m *Net) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSasl()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NetValidationError{
					field:  "Sasl",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NetValidationError{
					field:  "Sasl",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSasl()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NetValidationError{
				field:  "Sasl",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTls()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NetValidationError{
					field:  "Tls",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NetValidationError{
					field:  "Tls",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTls()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NetValidationError{
				field:  "Tls",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return NetMultiError(errors)
	}

	return nil
}

// NetMultiError is an error wrapping multiple validation errors returned by
// Net.ValidateAll() if the designated constraints aren't met.
type NetMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NetMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NetMultiError) AllErrors() []error { return m }

// NetValidationError is the validation error returned by Net.Validate if the
// designated constraints aren't met.
type NetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NetValidationError) ErrorName() string { return "NetValidationError" }

// Error satisfies the builtin error interface
func (e NetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNet.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NetValidationError{}

// Validate checks the field values on Conf with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Conf) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Conf with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ConfMultiError, or nil if none found.
func (m *Conf) ValidateAll() error {
	return m.validate(true)
}

func (m *Conf) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetNet()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ConfValidationError{
					field:  "Net",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ConfValidationError{
					field:  "Net",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNet()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConfValidationError{
				field:  "Net",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Group

	// no validation rules for Topic

	// no validation rules for Offset

	if all {
		switch v := interface{}(m.GetReadTimeout()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ConfValidationError{
					field:  "ReadTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ConfValidationError{
					field:  "ReadTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReadTimeout()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConfValidationError{
				field:  "ReadTimeout",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetWriteTimeout()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ConfValidationError{
					field:  "WriteTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ConfValidationError{
					field:  "WriteTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetWriteTimeout()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConfValidationError{
				field:  "WriteTimeout",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Acks

	if len(errors) > 0 {
		return ConfMultiError(errors)
	}

	return nil
}

// ConfMultiError is an error wrapping multiple validation errors returned by
// Conf.ValidateAll() if the designated constraints aren't met.
type ConfMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConfMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConfMultiError) AllErrors() []error { return m }

// ConfValidationError is the validation error returned by Conf.Validate if the
// designated constraints aren't met.
type ConfValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConfValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConfValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConfValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConfValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConfValidationError) ErrorName() string { return "ConfValidationError" }

// Error satisfies the builtin error interface
func (e ConfValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConf.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConfValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConfValidationError{}

// Validate checks the field values on Net_SASL with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Net_SASL) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Net_SASL with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Net_SASLMultiError, or nil
// if none found.
func (m *Net_SASL) ValidateAll() error {
	return m.validate(true)
}

func (m *Net_SASL) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Enable

	// no validation rules for User

	// no validation rules for Password

	if len(errors) > 0 {
		return Net_SASLMultiError(errors)
	}

	return nil
}

// Net_SASLMultiError is an error wrapping multiple validation errors returned
// by Net_SASL.ValidateAll() if the designated constraints aren't met.
type Net_SASLMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Net_SASLMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Net_SASLMultiError) AllErrors() []error { return m }

// Net_SASLValidationError is the validation error returned by
// Net_SASL.Validate if the designated constraints aren't met.
type Net_SASLValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Net_SASLValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Net_SASLValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Net_SASLValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Net_SASLValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Net_SASLValidationError) ErrorName() string { return "Net_SASLValidationError" }

// Error satisfies the builtin error interface
func (e Net_SASLValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNet_SASL.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Net_SASLValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Net_SASLValidationError{}

// Validate checks the field values on Net_TLS with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Net_TLS) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Net_TLS with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in Net_TLSMultiError, or nil if none found.
func (m *Net_TLS) ValidateAll() error {
	return m.validate(true)
}

func (m *Net_TLS) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Enable

	// no validation rules for RootCa

	// no validation rules for Jks

	// no validation rules for Password

	// no validation rules for Cert

	// no validation rules for Key

	if len(errors) > 0 {
		return Net_TLSMultiError(errors)
	}

	return nil
}

// Net_TLSMultiError is an error wrapping multiple validation errors returned
// by Net_TLS.ValidateAll() if the designated constraints aren't met.
type Net_TLSMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Net_TLSMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Net_TLSMultiError) AllErrors() []error { return m }

// Net_TLSValidationError is the validation error returned by Net_TLS.Validate
// if the designated constraints aren't met.
type Net_TLSValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Net_TLSValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Net_TLSValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Net_TLSValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Net_TLSValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Net_TLSValidationError) ErrorName() string { return "Net_TLSValidationError" }

// Error satisfies the builtin error interface
func (e Net_TLSValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNet_TLS.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Net_TLSValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Net_TLSValidationError{}
